# -*- coding: utf-8 -*-
"""model_final.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1_OAnyxnmget5ggHAFi7JwBxwufkIHMG5
"""

!nvidia-smi

import os
HOME = os.getcwd()
print(HOME)

# Commented out IPython magic to ensure Python compatibility.
!git clone https://github.com/noorkhokhar99/yolov9.git
# %cd yolov9
!pip install -r requirements.txt -q

!pip install -q roboflow

import roboflow

from IPython.display import Image

!mkdir -p {HOME}/weights

!wget -P {HOME}/weights -q https://github.com/WongKinYiu/yolov9/releases/download/v0.1/yolov9-c.pt
!wget -P {HOME}/weights -q https://github.com/WongKinYiu/yolov9/releases/download/v0.1/yolov9-e.pt
!wget -P {HOME}/weights -q https://github.com/WongKinYiu/yolov9/releases/download/v0.1/gelan-c.pt
!wget -P {HOME}/weights -q https://github.com/WongKinYiu/yolov9/releases/download/v0.1/gelan-e.pt

!ls -la {HOME}/weights

!wget -P {HOME}/yolov9 -q https://github.com/noorkhokhar99/yolov9-real-time-webcam/blob/main/dmeo.png

SOURCE_IMAGE_PATH = f"{HOME}/yolov9/dmeo.png"

!python detect.py --weights {HOME}/weights/yolov9-c.pt --conf 0.1 --source {HOME}/DSC08867.JPG --device 0

Image(filename=f"{HOME}/yolov9/runs/detect/exp2/DSC08867.JPG", width=600)

# Commented out IPython magic to ensure Python compatibility.
# %cd {HOME}/yolov9

!pip install roboflow

from roboflow import Roboflow
rf = Roboflow(api_key="KyfaeBEZv2e6LTYXJn78")
project = rf.workspace("sagemcom-nhlr3").project("night-vision-mzy8e")
version = project.version(3)
dataset = version.download("yolov9")

# Commented out IPython magic to ensure Python compatibility.
# %cd {HOME}/yolov9

!python train.py \
--batch 16 --epochs 8 --img 640 --device 0 --min-items 0 --close-mosaic 15 \
--data {dataset.location}/data.yaml \
--weights {HOME}/weights/gelan-c.pt \
--cfg models/detect/gelan-c.yaml \
--hyp hyp.scratch-high.yaml

from IPython.display import Image
!ls {HOME}/yolov9/runs/train/exp/

Image(filename=f"{HOME}/yolov9/runs/train/exp/results.png", width=1000)

Image(filename="/content/yolov9/runs/train/exp/confusion_matrix.png", width=1000)

Image(filename=f"{HOME}/yolov9/runs/train/exp/val_batch0_pred.jpg", width=1000)

# Commented out IPython magic to ensure Python compatibility.
# %cd {HOME}/yolov9

!python val.py \
--img 640 --batch 32 --conf 0.001 --iou 0.7 --device 0 \
--data {dataset.location}/data.yaml \
--weights {HOME}/yolov9/runs/train/exp/weights/best.pt

!python detect.py \
--img 1280 --conf 0.1 --device 0 \
--weights {HOME}/yolov9/runs/train/exp/weights/best.pt \
--source {dataset.location}/valid/images

import glob
from IPython.display import Image, display

for image_path in glob.glob(f'{HOME}/yolov9/runs/detect/exp/*.jpg')[:3]:
      display(Image(filename=image_path, width=600))
      print("\n")

!pip install -q inference supervision